### PR TITLE
Update both package names with hyphen and underscore

### PR DESCRIPTION
**Pull request by tasansal**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tasansal** [comment]
@alexmojaki, @ocefpaf I think this makes sense, can you take a quick look?

**Comment by tasansal** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
I fixed the name and the re-rendering but note that, for some reason, a package was already uploaded recently. Maybe from attempt to do this without forking?

**Comment by tasansal** [comment]
Maybe, I did rename the package at some point and reran the recipe. Thanks for your help! I'll merge this in

**Pull request merged**
